import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Header from "~/components/Header";
import Container from "~/components/Container";
import GreenBabyBottle from "~/assets/GreenBabyBottle";

export default function CountryProfile() {
  const { data: sessionData, status } = useSession();
  const { clientId } = useRouter().query;

  return (
    <>
      <Head>
        <title>Benefitsphere - Risk Benefit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container>
          Country Profile <GreenBabyBottle width={50} height={50} />
        </Container>
      </main>
    </>
  );
}
