import Head from "next/head";
import { useRouter } from "next/router";
import Header from "~/components/Header";
import Container from "~/components/Container";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "~/utils/api";

const tableClass = "text-left pl-2 py-2";
const tableClassBold = "text-left pl-2 py-2 font-bold";
const planDetailsClass =
  "divide-x divide-white odd:bg-slate-100 even:bg-tertiary-lt";
const designDetailsClass =
  "divide-x divide-white odd:bg-slate-100 even:bg-secondary-lt";
const financialDetailsClass =
  "divide-x divide-white odd:bg-slate-100 even:bg-danger-lt";
const adminDetailsClass =
  "divide-x divide-white odd:bg-slate-100 even:bg-info-lt";

const coverageTypes = [
  "Life",
  "Accidental Death and Dismemberment",
  "Total and Permanent Disability",
];

const eligibility = [
  "All Employees",
  "Sales",
  "Manufacturing",
  "Hourly",
  "Salaried",
  "Professional",
  "Management",
  "Executives",
];

const countries = ["Canada", "USA", "UK", "Australia"];

const currencies = ["CAD", "USD", "GBP", "AUD"];

const employeeContributionOptions = ["None", "Fully employee paid", "Other"];

const employerContributionOptions = ["None", "Fully Employer paid", "Other"];

const insurers = ["Canada Life", "Sun Life", "Manulife", "Great West Life"];

export default function EditRiskPlan() {
  const { id } = useRouter().query;
  const idString = typeof id === "string" ? id : "";

  const { data: riskPlanDetails } =
    api.riskPlan.getRiskPlanDetailsById.useQuery({
      riskPlanId: Number(idString),
    });
  console.log(riskPlanDetails);
  return (
    <>
      <Head>
        <title>Benefitsphere - Edit Risk Benefit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          <div>
            <div className="flex justify-between">
              <h1 className="text-3xl font-bold">Life Plan Details Editing</h1>
              <Link href={`/risk/${id}`}>
                <button className="bg-primary hover:bg-tertiary rounded-lg px-4 py-1 text-lg font-bold text-white">
                  Save
                </button>
              </Link>
            </div>
            <div className="ml-4">
              <div>
                <h2 className="my-4 block text-xl font-semibold ">
                  Plan Information
                </h2>
                <table className="min-w-full divide-x divide-y divide-white ">
                  <thead>
                    <tr className="bg-primary divide-x divide-white text-white">
                      <th className="w-1/4 py-2 pl-2 text-left">Category</th>
                      <th className="w-3/4 py-2 pl-2 text-left">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className={planDetailsClass}>
                      <td className={tableClassBold}>Country</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {countries.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                      </td>
                    </tr>
                    <tr className={planDetailsClass}>
                      <td className={tableClassBold}>Currency</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {currencies.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                      </td>
                    </tr>
                    <tr className={planDetailsClass}>
                      <td className={tableClassBold}>
                        Is this a supplemental group benefit?
                      </td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          <option>Yes</option>
                          <option>No</option>
                        </select>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div>
                <h2 className="text-secondary my-4 block text-xl font-semibold">
                  Design Details
                </h2>
                <table className="min-w-full divide-x divide-y divide-white ">
                  <thead>
                    <tr className="bg-secondary divide-x divide-white text-white">
                      <th className="w-1/4 py-2 pl-2 text-left">Category</th>
                      <th className="w-3/4 py-2 pl-2 text-left">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="divide-x divide-white bg-slate-100">
                      <td className={tableClassBold}>Coverage Type</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {coverageTypes.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Eligibility</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {eligibility.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Benefit Form</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          <option>Fixed Amount</option>
                          <option>Salary Multiple</option>
                        </select>
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Benefit Description</td>
                      <td className={tableClass}>
                        <div className="flex">
                          <input
                            type="number"
                            className="w-12 rounded border border-slate-500 px-1 py-0.5"
                          />
                          <p className="ml-2">x</p>
                          <select className="ml-2 w-1/5 rounded border border-slate-500 py-0.5">
                            <option>Annual Base Salary</option>
                            <option>Monthly Base Salary</option>
                          </select>{" "}
                        </div>
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Non-evidence Limit</td>
                      <td className={tableClass}>
                        CAD{" "}
                        <input
                          type="number"
                          className="rounded border border-slate-500 px-1 py-0.5"
                        />
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Benefit Maximum</td>
                      <td className={tableClass}>
                        CAD{" "}
                        <input
                          type="number"
                          className="rounded border border-slate-500 px-1 py-0.5"
                        />
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Employee Contribution</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {employeeContributionOptions.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                        <input
                          type="text"
                          className="mx-4 w-3/5 rounded border border-slate-500 pl-2"
                        />
                      </td>
                    </tr>
                    <tr className={designDetailsClass}>
                      <td className={tableClassBold}>Employer Contribution</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {employerContributionOptions.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                        <input
                          type="text"
                          className="mx-4 w-3/5 rounded border border-slate-500 pl-2"
                        />
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div>
                <h2 className="text-danger my-4 block text-xl font-semibold ">
                  Financial Details
                </h2>
                <table className="min-w-full divide-x divide-y divide-white ">
                  <thead>
                    <tr className="bg-danger divide-x divide-white text-white">
                      <th className="w-1/4 py-2 pl-2 text-left">Category</th>
                      <th className="w-3/4 py-2 pl-2 text-left">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Insurer</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          {insurers.map((item, idx) => (
                            <option key={idx}>{item}</option>
                          ))}
                        </select>
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Policy Number</td>
                      <td className={tableClass}>
                        <input
                          type="text"
                          className="w-2/5 rounded border border-slate-500 pl-2"
                        />
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Policy Period</td>
                      <td className={tableClass}>
                        <div className="flex">
                          <input
                            type="date"
                            className="rounded border border-slate-500 pl-2"
                          />
                          <p className="mx-2">to</p>
                          <input
                            type="date"
                            className="rounded border border-slate-500 pl-2"
                          />
                        </div>
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Intermediaries</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          <option>Broker</option>
                          <option>Agent</option>
                          <option>Consultant</option>
                          <option>Other</option>
                        </select>
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Intermediary</td>
                      <td className={tableClass}>
                        <input
                          type="text"
                          className="w-2/5 rounded border border-slate-500 pl-2"
                        />
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Remuneration Method</td>
                      <td className={tableClass}>
                        <select className="w-1/5 rounded border border-slate-500">
                          <option>Flat Commission</option>
                          <option>Flat Fee</option>
                          <option>Other</option>
                        </select>
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Remuneration Amount</td>
                      <td className={tableClass}>
                        <div className="flex">
                          <input
                            type="number"
                            className="w-12 rounded border border-slate-500 pl-2 "
                          />{" "}
                          <p className="pl-2">% of premiums</p>
                        </div>
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Total Sum Insured</td>
                      <td className={tableClass}>
                        CAD{" "}
                        <input
                          type="number"
                          className="rounded border border-slate-500 pl-2 "
                        />
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Total Premiums</td>
                      <td className={tableClass}>
                        CAD{" "}
                        <input
                          type="number"
                          className="rounded border border-slate-500 pl-2 "
                        />
                      </td>
                    </tr>
                    <tr className={financialDetailsClass}>
                      <td className={tableClassBold}>Headcount</td>
                      <td className={tableClass}>
                        <input
                          type="number"
                          className="rounded border border-slate-500 pl-2 "
                        />
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div>
                <h2 className="text-info my-4 block text-xl font-semibold ">
                  Administration Details
                </h2>
                <table className="min-w-full divide-x divide-y divide-white ">
                  <thead>
                    <tr className="bg-info divide-x divide-white text-white">
                      <th className="w-1/4 py-2 pl-2 text-left">Category</th>
                      <th className="w-3/4 py-2 pl-2 text-left">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className={adminDetailsClass}>
                      <td className={tableClassBold}>
                        Policy Cancellation Period
                      </td>
                      <td className={tableClass}>3 months</td>
                    </tr>
                    <tr className={adminDetailsClass}>
                      <td className={tableClassBold}>Invoicing</td>
                      <td className={tableClass}>
                        <textarea
                          className="w-3/5 rounded border border-slate-500 pl-2"
                          rows={3}
                        />
                      </td>
                    </tr>
                    <tr className={adminDetailsClass}>
                      <td className={tableClassBold}>Employee Enrollment</td>
                      <td className={tableClass}>
                        <textarea
                          className="w-3/5 rounded border border-slate-500 pl-2"
                          rows={3}
                        />
                      </td>
                    </tr>
                    <tr className={adminDetailsClass}>
                      <td className={tableClassBold}>Employee Termination</td>
                      <td className={tableClass}>
                        <textarea
                          className="w-3/5 rounded border border-slate-500 pl-2"
                          rows={3}
                        />
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </Container>
      </main>
    </>
  );
}
