import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Router from "next/router";
import Header from "~/components/Header";
import Container from "~/components/Container";

export default function Dashboard() {
  const { data: sessionData, status } = useSession();
  const { id } = useRouter().query;
  const idString = typeof id === "string" ? id : "";

  return (
    <>
      <Head>
        <title>Benefitsphere - Risk Benefit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          <h1 className="text-3xl font-bold">Risk Benefit Details</h1>

          <h2 className="my-4 block text-xl font-semibold ">Risk Plans</h2>
        </Container>
      </main>
    </>
  );
}
