import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Header from "~/components/Header";
import Container from "~/components/Container";

export default function Rewards() {
  const { data: sessionData, status } = useSession();
  const { clientId } = useRouter().query;

  return (
    <>
      <Head>
        <title>Benefitsphere - Risk Benefit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          <h1 className="text-4xl font-bold">Welcome!</h1>
          <p>Test</p>
        </Container>
      </main>
    </>
  );
}
