import Head from "next/head";
import { AddClientContainer } from "~/components/AddClientContainer";
import { Footer } from "~/components/Footer";
import Header from "~/components/Header";

export default function AddClient() {
  return (
    <>
      <Head>
        <title>Add a Client</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <AddClientContainer />
        <Footer />
      </main>
    </>
  );
}
