import Head from "next/head";
import { useState } from "react";
import { useSession } from "next-auth/react";
import Router from "next/router";
import { api } from "~/utils/api";
import Image from "next/image";
import { Footer } from "~/components/Footer";
import Header from "~/components/Header";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";
import { Input } from "~/components/ui/input";

const currencies = ["USD", "EUR", "GBP", "CAD", "AUD"];
const industries = [
  "High Tech",
  "Finance",
  "Healthcare",
  "Retail",
  "Manufacturing",
];

export default function AddClient() {
  const { data: sessionData } = useSession();
  console.log(sessionData);
  const [clientName, setClientName] = useState("");
  const [selectedIndustry, setSelectedIndustry] = useState(
    industries[0] ?? "High Tech",
  );
  const [selectedCurrency, setSelectedCurrency] = useState(
    currencies[0] ?? "USD",
  );

  const createClient = api.client.create.useMutation();

  const handleAddClient = () => {
    if (!clientName) {
      return;
    }

    createClient.mutate({
      clientName,
      industry: selectedIndustry,
      baseCurrency: selectedCurrency,
    });
    Router.push("/").catch((err) => console.log(err));
  };

  return (
    <>
      <Head>
        <title>Add a Client</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative text-primary">
        <Header />
        <div className="flex h-dvh items-center justify-center bg-gradient-to-br from-tertiary to-secondary p-6 pb-72 ">
          <div className="w-1/5 flex-col justify-between rounded border border-gray-100 bg-white px-4 shadow-2xl">
            <div>
              <div className="">
                <h2 className="pb-2 text-2xl font-bold text-danger">
                  Add a Client
                </h2>
              </div>
              <div className="mb-2">
                <label
                  htmlFor="client-name"
                  className="block text-sm font-medium leading-6"
                >
                  Client Name
                </label>
                <Input
                  type="text"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                  className="w-72"
                />
              </div>
              <div className="mb-2">
                <label
                  htmlFor="industry"
                  className="block text-sm font-medium leading-6"
                >
                  Industry
                </label>
                <AddClientSelect
                  placeholder="Select Industry"
                  options={industries}
                  value={selectedIndustry}
                  setValue={setSelectedIndustry}
                />
              </div>
              <div>
                <label
                  htmlFor="currency"
                  className="block text-sm font-medium leading-6"
                >
                  Currency
                </label>
                <AddClientSelect
                  placeholder="Select Currency"
                  options={currencies}
                  value={selectedCurrency}
                  setValue={setSelectedCurrency}
                />
              </div>
              <div>
                <button
                  className="my-4 rounded bg-primary px-4 py-2 text-white hover:bg-primary-lt"
                  onClick={() => handleAddClient()}
                >
                  {" "}
                  Add client
                </button>
              </div>
            </div>
          </div>
          <div className="absolute bottom-24 right-0">
            <Image src="/RedDoor.png" alt="Red Door" width={500} height={300} />
          </div>
        </div>

        <Footer />
      </main>
    </>
  );
}

type AddClientSelectProps = {
  placeholder: string;
  options: string[];
  value: string;
  setValue: (value: string) => void;
};

const AddClientSelect: React.FC<AddClientSelectProps> = ({
  placeholder,
  options,
  value,
  setValue,
}) => {
  return (
    <Select
      value={value}
      onValueChange={(value) => {
        setValue(value);
      }}
    >
      <SelectTrigger className="w-72 ">
        <SelectValue placeholder={placeholder} />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          {options.map((item, idx) => (
            <SelectItem key={idx} value={item ?? ""}>
              {item}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
};
