import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { AddClientContainer } from "~/components/AddClientContainer";

import { api } from "~/utils/api";

export default function AddClient() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Add a Client</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center ">
        <AddClientContainer />
      </main>
    </>
  );
}
