import React from "react";
import Head from "next/head";
import Container from "~/components/Container";
import Header from "~/components/Header";
import { api } from "~/utils/api";
import { Footer } from "~/components/Footer";
import { useSession } from "next-auth/react";

export default function UserManagement() {
  const { data: sessionData } = useSession();
  console.log(sessionData);

  const { data: clientData } = api.client.getClientDetailsById.useQuery({
    clientId: sessionData?.user?.activeClient || 0,
  });

  const { data: countries } = api.country.getCountries.useQuery();

  return (
    <>
      <Head>
        <title>Benefitsphere - Client Management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          <h1 className="pb-2 text-3xl font-bold">Client Management</h1>
          <div className="rounded-md border border-slate-400 px-6 py-4 shadow-lg">
            <div className="mx-12 flex justify-between">
              <div>
                <label className="block text-xs font-medium">Client Name</label>
                <h2 className="text-2xl font-semibold text-danger">
                  {" "}
                  {clientData?.clientName}
                </h2>
              </div>
              <div>
                <label className="block text-xs font-medium">Industry</label>
                <h2 className="text-2xl font-semibold text-danger">
                  {" "}
                  {clientData?.industry}
                </h2>
              </div>
              <div>
                <label className="block text-xs font-medium">
                  Base Currency
                </label>
                <h2 className="text-2xl font-semibold text-danger">
                  {" "}
                  {clientData?.baseCurrency}
                </h2>
              </div>
            </div>
            <div className="mx-12 mt-4">
              <label className="block text-xs font-medium">Company URL</label>
              <h2 className="text-2xl font-semibold text-danger">TBD</h2>
            </div>
            <div className="mx-12 mt-4">
              <label className="block text-xs font-medium">Countries</label>
              <div className="px-2 py-2 font-semibold">
                <select>
                  {countries?.map((country) => (
                    <option key={country.id} value={country.id}>
                      {country.country}
                    </option>
                  ))}
                </select>
                <button className="ml-4 rounded bg-primary px-2 py-1 text-white hover:bg-primary-lt">
                  Add Countries
                </button>
              </div>
            </div>
            <div className="mx-12 mt-4 grid grid-cols-3 gap-4">
              <div className="">United States</div>
              <div className="">Canada</div>
              <div className="">Canada</div>
              <div className="">Canada</div>
            </div>
          </div>
        </Container>
        <Footer />
      </main>
    </>
  );
}
