import Head from "next/head";
import Container from "~/components/Container";
import Header from "~/components/Header";

import { api } from "~/utils/api";

export default function ClientManagement() {
  const { data: userData } = api.user.getUsers.useQuery();
  const { data: clientData } = api.client.getClients.useQuery();
  const { data: usersToClientsData } = api.client.getUsersToClients.useQuery();

  console.log(usersToClientsData);

  return (
    <>
      <Head>
        <title>Client Management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container>
          <table className="min-w-full divide-y divide-gray-200">
            <thead>
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                  Client
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                  User
                </th>
              </tr>
            </thead>
            <tbody>
              {usersToClientsData?.map((userToClient) => (
                <tr key={userToClient.client.id + userToClient.user.id}>
                  <td className="whitespace-nowrap px-6 py-4 text-sm font-medium text-gray-900">
                    {userToClient.client.clientName}
                  </td>
                  <td className="whitespace-nowrap px-6 py-4 text-sm font-medium text-gray-900">
                    {userToClient.user.name}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Container>
      </main>
    </>
  );
}
