import Head from "next/head";
import { useState, useEffect } from "react";
import Container from "~/components/Container";
import { Footer } from "~/components/Footer";
import Header from "~/components/Header";
import { useSession } from "next-auth/react";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";
import { CustomSelect } from "~/components/CustomSelect";
import { Checkbox } from "~/components/ui/checkbox";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table";
import { Textarea } from "~/components/ui/textarea";
import Link from "next/link";

export default function GenerateRewards() {
  const { data: sessionData } = useSession();
  const [step, setStep] = useState(1);
  const [country, setCountry] = useState("");
  const [loading, setLoading] = useState(false);
  const [chosenPlans, setChosenPlans] = useState<number[]>([]);

  const { data: clientData } = api.client.getClientDetailsById.useQuery({
    clientId: sessionData?.user.activeClient ?? 0,
  });

  const NoRewards = (
    <div className="flex flex-col items-center justify-center">
      <h1 className="text-3xl font-bold">No rewards to generate</h1>
      <button className="my-1 rounded bg-primary px-2 py-0.5 text-white hover:bg-primary-lt">
        Click here to generate a rewards page
      </button>
    </div>
  );

  const Rewards = (
    <div className="flex items-center justify-center">
      <h1 className="text-3xl font-bold">Rewards are generated</h1>
    </div>
  );

  return (
    <>
      <Head>
        <title>Benefitsphere - Generate Rewards Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          {clientData?.rewardsWelcomeMessage === "" ? NoRewards : Rewards}
        </Container>
        <Footer />
      </main>
    </>
  );
}
