import { useSession } from "next-auth/react";
import Head from "next/head";
import Container from "~/components/Container";
import Header from "~/components/Header";
import useClientSelector from "~/hooks/useClientSelector";
import { api } from "~/utils/api";

const tableClass = "text-left pl-2";

export default function Dashboard() {
  const { data: sessionData } = useSession();
  const { data: riskPlans } = api.riskPlan.getRiskPlansByClientId.useQuery({
    clientId: sessionData?.user.activeClient ?? 0,
  });

  console.log(riskPlans);

  useClientSelector();

  return (
    <>
      <Head>
        <title>Benefitsphere - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          <h1 className="text-3xl font-bold">Benefits Homepage</h1>

          <h2 className="my-4 block text-xl font-semibold ">Risk Plans</h2>
          <div>
            <table className="min-w-full divide-x divide-y divide-white ">
              <thead>
                <tr className="bg-primary divide-x divide-white text-white">
                  <th className={tableClass}>Country</th>
                  <th className={tableClass}>Benefit Type</th>
                  <th className={tableClass}>Benefit Name</th>
                </tr>
              </thead>
              <tbody>
                {riskPlans?.map((riskPlan) => (
                  <tr
                    key={riskPlan.field1}
                    className="divide-x divide-white bg-slate-100"
                  >
                    <td className={tableClass}>{riskPlan.field2}</td>
                    <td className={tableClass}>{riskPlan.field3}</td>
                    <td className={tableClass}>{riskPlan.field4}</td>
                  </tr>
                ))}
                <tr key={2} className="bg-tertiary-lt divide-x divide-white">
                  <td className={tableClass}>United Kingdom</td>
                  <td className={tableClass}>AD&D</td>
                  <td className={tableClass}>UK - AD&D Plan</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Container>
      </main>
    </>
  );
}
