import { useState } from "react";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Container from "~/components/Container";
import { Footer } from "~/components/Footer";
import Header from "~/components/Header";
import useClientSelector from "~/hooks/useClientSelector";
import { api } from "~/utils/api";
import { AddBenefitModal } from "~/components/AddBenefitModal";

const tableClass = "text-left pl-2";
const tableHeadClass = "text-left pl-2 py-2";
const isLoading = (status: string) => status === "loading";

export default function Dashboard() {
  const [openModal, setOpenModal] = useState(false);
  const { data: sessionData, status: sessionStatus } = useSession();
  const { data: clientData, status: clientStatus } =
    api.client.getClientDetailsById.useQuery({
      clientId: sessionData?.user.activeClient ?? 0,
    });
  const {
    data: riskPlans,
    status: riskStatus,
    refetch: refetchRiskPlans,
  } = api.riskPlan.getRiskPlansByClientId.useQuery({
    clientId: sessionData?.user.activeClient ?? 0,
  });

  useClientSelector();
  if (
    isLoading(sessionStatus) ||
    isLoading(clientStatus) ||
    isLoading(riskStatus)
  ) {
    return <p>Loading...</p>;
  }

  return (
    <>
      <Head>
        <title>Benefitsphere - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-primary">
        <Header />
        <Container>
          <div className="flex items-center justify-between">
            <h1 className="text-3xl font-bold">Benefit Homepage</h1>
            <AddBenefitModal />
          </div>

          <h2 className="my-4 block text-xl font-semibold ">Risk Plans</h2>
          <div>
            <table className="min-w-full divide-x divide-y divide-white ">
              <thead>
                <tr className="divide-x divide-white bg-primary text-white">
                  <th className={tableHeadClass}>Country</th>
                  <th className={tableHeadClass}>Benefit Type</th>
                  <th className={tableHeadClass}>Benefit Name</th>
                  <th className={tableHeadClass}>More Details</th>
                </tr>
              </thead>
              <tbody>
                {riskPlans?.map((riskPlan) => (
                  <tr
                    key={riskPlan.field1}
                    className="divide-x divide-white odd:bg-slate-100 even:bg-tertiary-lt"
                  >
                    <td className={tableClass}>{riskPlan.field2}</td>
                    <td className={tableClass}>{riskPlan.field3}</td>
                    <td className={tableClass}>{riskPlan.field4}</td>
                    <td className={tableClass}>
                      <Link
                        href={`risk/${riskPlan.field1}`}
                        className="my-1 rounded bg-primary px-2 py-0.5 text-white hover:bg-primary-lt"
                      >
                        Details
                      </Link>
                    </td>
                  </tr>
                ))}
                <tr key={2} className="divide-x divide-white bg-tertiary-lt">
                  <td className={tableClass}>United Kingdom</td>
                  <td className={tableClass}>AD&D</td>
                  <td className={tableClass}>UK - AD&D Plan</td>
                  <td className={tableClass}>
                    <button className="my-1 rounded bg-primary px-2 py-0.5 text-white hover:bg-primary-lt">
                      Details
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </Container>
        <Footer />
      </main>
    </>
  );
}
