import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const usersToClients = api.client.getUsersToClients.useQuery();
  const { data: sessionData } = useSession();
  const { data: userData } = api.user.getUsers.useQuery();

  console.log(userData);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center ">
        Hello world
      </main>
    </>
  );
}
