import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Container from "~/components/Container";
import Header from "~/components/Header";
import useClientSelector from "~/hooks/useClientSelector";
import { api } from "~/utils/api";

export default function Life() {
  const { data: sessionData } = useSession();
  useClientSelector();

  return (
    <>
      <Head>
        <title>Life benefit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Container>Life benefit</Container>
      </main>
    </>
  );
}
